version: "3.9"
services:
  mysql:
    image: "mysql:8.0.31"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
