spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa2v2180vgZLAPgY697
            client-secret: hqmOdtos6pb22yaEC_n1iDDIfxNpuo-39tDkzNtm
        provider:
          okta:
            issuer-uri: https://trial-7328584.okta.com/oauth2/default

# See https://github.com/spring-projects/spring-security/blob/5.4.1/samples/boot/oauth2login/README.adoc#okta-login